config:
    output_directory: ./hirax/drift_products/
    beamtransfers: true
    try_resume: true
    truncate: true
    skip_svd: false
    skip_svd_inv: true
    kltransform: false
    psfisher: false
telescope:
    type: HIRAXSurvey
    ndays: 120
    tsys_flat: 50
    maxlength: 70.0
    min_u: 6.5
    min_v: 8.5
    freq_lower: 600
    freq_upper: 700
    freq_mode: edge
    num_freq: 64
    beam_spec:
        type: gaussian
        diameter: 6
    elevation_start: -10
    elevation_stop: 10
    npointings: 9
kltransform:
-   type: DoubleKL
    name: dk_5thresh_fg_1000thresh
    inverse: true
    threshold: 5.0
    use_thermal: true
    use_foregrounds: true
    use_polarised: true
    foreground_threshold: 1000.0
-   type: DoubleKL
    name: dk_0thresh_fg_1000thresh
    inverse: true
    threshold: 0.0
    use_thermal: true
    use_foregrounds: true
    use_polarised: true
    foreground_threshold: 1000.0
-   type: DoubleKL
    name: dk_0thresh_fg_10thresh
    inverse: true
    threshold: 0.0
    use_thermal: true
    use_foregrounds: true
    use_polarised: true
    foreground_threshold: 10.0
-   type: DoubleKL
    name: dk_0thresh_fg_1thresh
    inverse: true
    threshold: 0.0
    use_thermal: true
    use_foregrounds: true
    use_polarised: true
    foreground_threshold: 1.0
-   type: KLTransform
    name: kl_0thresh_nofg
    inverse: true
    threshold: 0.0
    use_thermal: true
    use_foregrounds: false
    use_polarised: true
psfisher:
-   type: MonteCarlo
    name: psmc_dk_5thresh_fg_1000thresh_1threshold
    klname: dk_5thresh_fg_1000thresh
    threshold: 1.0
    bandtype: cartesian
    nsamples: 20000
    kpar_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.3
        num: 31
    kperp_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.2
        num: 15
-   type: MonteCarlo
    name: psmc_dk_0thresh_fg_1000thresh_1threshold
    klname: dk_0thresh_fg_1000thresh
    threshold: 1.0
    bandtype: cartesian
    nsamples: 20000
    kpar_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.3
        num: 31
    kperp_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.2
        num: 15
-   type: MonteCarlo
    name: psmc_dk_0thresh_fg_10thresh_1threshold
    klname: dk_0thresh_fg_10thresh
    threshold: 1.0
    bandtype: cartesian
    nsamples: 20000
    kpar_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.3
        num: 31
    kperp_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.2
        num: 15
-   type: MonteCarlo
    name: psmc_dk_0thresh_fg_1thresh_1threshold
    klname: dk_0thresh_fg_1thresh
    threshold: 1.0
    bandtype: cartesian
    nsamples: 20000
    kpar_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.3
        num: 31
    kperp_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.2
        num: 15
-   type: MonteCarlo
    name: psmc_kl_0thresh_nofg_1threshold
    klname: kl_0thresh_nofg
    threshold: 1.0
    bandtype: cartesian
    nsamples: 20000
    kpar_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.3
        num: 31
    kperp_bands:
    -   spacing: linear
        start: 0.0
        stop: 0.2
        num: 15
