pipeline:
    tasks:
        -   type:       draco.core.task.SetMPILogging

        -   type:       draco.core.io.LoadProductManager
            out:        pm
            params:
                product_directory:  './hirax/drift_prod_hirax_survey_49elem_7point_64bands'

        -   type:       draco.core.io.LoadFilesFromParams
            out:        sidereal_collated
            params:
              files:
                - './hirax/draco/sstream_wnoise_group_0.h5'

        -   type:       draco.analysis.transform.MModeTransform
            requires:   pm
            in:         sidereal_collated
            out:        mmodes

        -   type:       draco.analysis.fgfilter.SVDModeProject
            requires:   pm
            in:         mmodes
            out:        svdmodes

# dk_5thresh_fg_10thresh ------ 1

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_dk_5thresh_fg_10thresh
            params:
                klname: dk_5thresh_fg_10thresh 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_10thresh
            out:        psmc_uw_dk_5thresh_fg_10thresh
            params:
                psname: psmc_dk_5thresh_fg_10thresh_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_dk_5thresh_fg_10thresh_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_dk_5thresh_fg_10thresh
        #    out:        psmc_uc_dk_5thresh_fg_10thresh
        #    params:
        #        psname: psmc_dk_5thresh_fg_10thresh_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_dk_5thresh_fg_10thresh_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_10thresh
            out:        psmc_mv_dk_5thresh_fg_10thresh
            params:
                psname: psmc_dk_5thresh_fg_10thresh_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_dk_5thresh_fg_10thresh_'

# dk_5thresh_fg_100thresh ------ 2

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_dk_5thresh_fg_100thresh
            params:
                klname: dk_5thresh_fg_100thresh 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_100thresh
            out:        psmc_uw_dk_5thresh_fg_100thresh
            params:
                psname: psmc_dk_5thresh_fg_100thresh_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_dk_5thresh_fg_100thresh_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_dk_5thresh_fg_100thresh
        #    out:        psmc_uc_dk_5thresh_fg_100thresh
        #    params:
        #        psname: psmc_dk_5thresh_fg_100thresh_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_dk_5thresh_fg_100thresh_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_100thresh
            out:        psmc_mv_dk_5thresh_fg_100thresh
            params:
                psname: psmc_dk_5thresh_fg_100thresh_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_dk_5thresh_fg_100thresh_'

# dk_5thresh_fg_1000thresh ------ 3

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_dk_5thresh_fg_1000thresh
            params:
                klname: dk_5thresh_fg_1000thresh 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_1000thresh
            out:        psmc_uw_dk_5thresh_fg_1000thresh
            params:
                psname: psmc_dk_5thresh_fg_1000thresh_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_dk_5thresh_fg_1000thresh_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_dk_5thresh_fg_1000thresh
        #    out:        psmc_uc_dk_5thresh_fg_1000thresh
        #    params:
        #        psname: psmc_dk_5thresh_fg_1000thresh_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_dk_5thresh_fg_1000thresh_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_1000thresh
            out:        psmc_mv_dk_5thresh_fg_1000thresh
            params:
                psname: psmc_dk_5thresh_fg_1000thresh_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_dk_5thresh_fg_1000thresh_'

# dk_10thresh_fg_100thresh ------ 4

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_dk_10thresh_fg_100thresh
            params:
                klname: dk_10thresh_fg_100thresh 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_10thresh_fg_100thresh
            out:        psmc_uw_dk_10thresh_fg_100thresh
            params:
                psname: psmc_dk_10thresh_fg_100thresh_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_dk_10thresh_fg_100thresh_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_dk_10thresh_fg_100thresh
        #    out:        psmc_uc_dk_10thresh_fg_100thresh
        #    params:
        #        psname: psmc_dk_10thresh_fg_100thresh_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_dk_10thresh_fg_100thresh_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_10thresh_fg_100thresh
            out:        psmc_mv_dk_10thresh_fg_100thresh
            params:
                psname: psmc_dk_10thresh_fg_100thresh_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_dk_10thresh_fg_100thresh_'

# dk_1thresh_fg_100thresh ------ 5

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_dk_1thresh_fg_100thresh
            params:
                klname: dk_1thresh_fg_100thresh 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_1thresh_fg_100thresh
            out:        psmc_uw_dk_1thresh_fg_100thresh
            params:
                psname: psmc_dk_1thresh_fg_100thresh_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_dk_1thresh_fg_100thresh_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_dk_1thresh_fg_100thresh
        #    out:        psmc_uc_dk_1thresh_fg_100thresh
        #    params:
        #        psname: psmc_dk_1thresh_fg_100thresh_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_dk_1thresh_fg_100thresh_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_1thresh_fg_100thresh
            out:        psmc_mv_dk_1thresh_fg_100thresh
            params:
                psname: psmc_dk_1thresh_fg_100thresh_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_dk_1thresh_fg_100thresh_'

# kl_0thresh_nofg ------ 6

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_kl_0thresh_nofg
            params:
                klname: kl_0thresh_nofg 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_0thresh_nofg
            out:        psmc_uw_kl_0thresh_nofg
            params:
                psname: psmc_kl_0thresh_nofg_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_kl_0thresh_nofg_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_kl_0thresh_nofg
        #    out:        psmc_uc_kl_0thresh_nofg
        #    params:
        #        psname: psmc_kl_0thresh_nofg_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_kl_0thresh_nofg_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_0thresh_nofg
            out:        psmc_mv_kl_0thresh_nofg
            params:
                psname: psmc_kl_0thresh_nofg_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_kl_0thresh_nofg_'

# kl_1thresh_nofg ------ 7

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_kl_1thresh_nofg
            params:
                klname: kl_1thresh_nofg 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_1thresh_nofg
            out:        psmc_uw_kl_1thresh_nofg
            params:
                psname: psmc_kl_1thresh_nofg_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_kl_1thresh_nofg_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_kl_1thresh_nofg
        #    out:        psmc_uc_kl_1thresh_nofg
        #    params:
        #        psname: psmc_kl_1thresh_nofg_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_kl_1thresh_nofg_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_1thresh_nofg
            out:        psmc_mv_kl_1thresh_nofg
            params:
                psname: psmc_kl_1thresh_nofg_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_kl_1thresh_nofg_'

# kl_5thresh_nofg ------ 8

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_kl_5thresh_nofg
            params:
                klname: kl_5thresh_nofg 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_5thresh_nofg
            out:        psmc_uw_kl_5thresh_nofg
            params:
                psname: psmc_kl_5thresh_nofg_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_kl_5thresh_nofg_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_kl_5thresh_nofg
        #    out:        psmc_uc_kl_5thresh_nofg
        #    params:
        #        psname: psmc_kl_5thresh_nofg_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_kl_5thresh_nofg_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_5thresh_nofg
            out:        psmc_mv_kl_5thresh_nofg
            params:
                psname: psmc_kl_5thresh_nofg_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_kl_5thresh_nofg_'

# kl_10thresh_nofg ------ 9

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_kl_10thresh_nofg
            params:
                klname: kl_10thresh_nofg 
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_10thresh_nofg
            out:        psmc_uw_kl_10thresh_nofg
            params:
                psname: psmc_kl_10thresh_nofg_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_kl_10thresh_nofg_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_kl_10thresh_nofg
        #    out:        psmc_uc_kl_10thresh_nofg
        #    params:
        #        psname: psmc_kl_10thresh_nofg_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_kl_10thresh_nofg_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_10thresh_nofg
            out:        psmc_mv_kl_10thresh_nofg
            params:
                psname: psmc_kl_10thresh_nofg_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_kl_10thresh_nofg_'

