config:
  beamtransfers: false
  kltransform: true
  output_directory: /gpfs/fs0/scratch/s/sievers/nistanev/mmode_runs_2023/survey_runs/base_400_500_gaussian_survey_center/hirax/drift_products
  psfisher: false
  skip_svd: true
  skip_svd_inv: true
  truncate: false
  try_resume: true
kltransform:
- foreground_threshold: 1000.0
  inverse: true
  name: dk_5thresh_fg_1000thresh
  threshold: 5.0
  type: DoubleKL
  use_foregrounds: true
  use_polarised: true
  use_thermal: true
- foreground_threshold: 1000.0
  inverse: true
  name: dk_0thresh_fg_1000thresh
  threshold: 0.0
  type: DoubleKL
  use_foregrounds: true
  use_polarised: true
  use_thermal: true
- foreground_threshold: 10.0
  inverse: true
  name: dk_0thresh_fg_10thresh
  threshold: 0.0
  type: DoubleKL
  use_foregrounds: true
  use_polarised: true
  use_thermal: true
- foreground_threshold: 1.0
  inverse: true
  name: dk_0thresh_fg_1thresh
  threshold: 0.0
  type: DoubleKL
  use_foregrounds: true
  use_polarised: true
  use_thermal: true
- inverse: true
  name: kl_0thresh_nofg
  threshold: 0.0
  type: KLTransform
  use_foregrounds: false
  use_polarised: true
  use_thermal: true
psfisher:
- bandtype: cartesian
  klname: dk_5thresh_fg_1000thresh
  kpar_bands:
  - num: 31
    spacing: linear
    start: 0.0
    stop: 0.3
  kperp_bands:
  - num: 15
    spacing: linear
    start: 0.0
    stop: 0.15
  name: psmc_dk_5thresh_fg_1000thresh_1threshold
  nsamples: 20000
  threshold: 1.0
  type: MonteCarlo
- bandtype: cartesian
  klname: dk_0thresh_fg_1000thresh
  kpar_bands:
  - num: 31
    spacing: linear
    start: 0.0
    stop: 0.3
  kperp_bands:
  - num: 15
    spacing: linear
    start: 0.0
    stop: 0.15
  name: psmc_dk_0thresh_fg_1000thresh_1threshold
  nsamples: 20000
  threshold: 1.0
  type: MonteCarlo
- bandtype: cartesian
  klname: dk_0thresh_fg_10thresh
  kpar_bands:
  - num: 31
    spacing: linear
    start: 0.0
    stop: 0.3
  kperp_bands:
  - num: 15
    spacing: linear
    start: 0.0
    stop: 0.15
  name: psmc_dk_0thresh_fg_10thresh_1threshold
  nsamples: 20000
  threshold: 1.0
  type: MonteCarlo
- bandtype: cartesian
  klname: dk_0thresh_fg_1thresh
  kpar_bands:
  - num: 31
    spacing: linear
    start: 0.0
    stop: 0.3
  kperp_bands:
  - num: 15
    spacing: linear
    start: 0.0
    stop: 0.15
  name: psmc_dk_0thresh_fg_1thresh_1threshold
  nsamples: 20000
  threshold: 1.0
  type: MonteCarlo
- bandtype: cartesian
  klname: kl_0thresh_nofg
  kpar_bands:
  - num: 31
    spacing: linear
    start: 0.0
    stop: 0.3
  kperp_bands:
  - num: 15
    spacing: linear
    start: 0.0
    stop: 0.15
  name: psmc_kl_0thresh_nofg_1threshold
  nsamples: 20000
  threshold: 1.0
  type: MonteCarlo
telescope:
  beam_spec:
    diameter: 6
    type: gaussian
  elevation_start: -10
  elevation_stop: 10
  freq_lower: 400
  freq_mode: edge
  freq_upper: 500
  maxlength: 70.0
  min_u: 6.5
  min_v: 8.5
  ndays: 120
  npointings: 9
  num_freq: 64
  tsys_flat: 50
  type: HIRAXSurvey
