pipeline:
    tasks:
        -   type:       draco.core.task.SetMPILogging

        -   type:       draco.core.io.LoadProductManager
            out:        pm
            params:
                product_directory:  './hirax/drift_prod_hirax_survey_49elem_7point_64bands'

        -   type:       draco.core.io.LoadFilesFromParams
            out:        sidereal_collated
            params:
              files:
                - './hirax/draco/sstream_wnoise_group_0.h5'

        -   type:       draco.analysis.transform.MModeTransform
            requires:   pm
            in:         sidereal_collated
            out:        mmodes

        -   type:       draco.analysis.fgfilter.SVDModeProject
            requires:   pm
            in:         mmodes
            out:        svdmodes


# dk_5thresh_fg_1000thresh ------ 3

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_dk_5thresh_fg_1000thresh
            params:
                klname: dk_5thresh_fg_1000thresh
                threshold: 1.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_1000thresh
            out:        psmc_uw_dk_5thresh_fg_1000thresh
            params:
                psname: psmc_dk_5thresh_fg_1000thresh_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_dk_5thresh_fg_1000thresh_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_dk_5thresh_fg_1000thresh
        #    out:        psmc_uc_dk_5thresh_fg_1000thresh
        #    params:
        #        psname: psmc_dk_5thresh_fg_1000thresh_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_dk_5thresh_fg_1000thresh_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_dk_5thresh_fg_1000thresh
            out:        psmc_mv_dk_5thresh_fg_1000thresh
            params:
                psname: psmc_dk_5thresh_fg_1000thresh_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_dk_5thresh_fg_1000thresh_'

# kl_0thresh_nofg ------ 6

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_kl_0thresh_nofg
            params:
                klname: kl_0thresh_nofg
                threshold: 0.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_0thresh_nofg
            out:        psmc_uw_kl_0thresh_nofg
            params:
                psname: psmc_kl_0thresh_nofg_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_kl_0thresh_nofg_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_kl_0thresh_nofg
        #    out:        psmc_uc_kl_0thresh_nofg
        #    params:
        #        psname: psmc_kl_0thresh_nofg_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_kl_0thresh_nofg_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_0thresh_nofg
            out:        psmc_mv_kl_0thresh_nofg
            params:
                psname: psmc_kl_0thresh_nofg_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_kl_0thresh_nofg_'

# kl_5thresh_nofg ------ 8

        -   type:       draco.analysis.fgfilter.KLModeProject
            requires:   pm
            in:         svdmodes
            out:        klmodes_kl_5thresh_nofg
            params:
                klname: kl_5thresh_nofg
                threshold: 0.0

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_5thresh_nofg
            out:        psmc_uw_kl_5thresh_nofg
            params:
                psname: psmc_kl_5thresh_nofg_1threshold
                pstype: unwindowed
                save:   Yes
                output_root: './hirax/draco/psmc_unwindowed_wnoise_fgfilter_kl_5thresh_nofg_'

        #-   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
        #    requires:   pm
        #    in:         klmodes_kl_5thresh_nofg
        #    out:        psmc_uc_kl_5thresh_nofg
        #    params:
        #        psname: psmc_kl_5thresh_nofg_1threshold
        #        pstype: uncorrelated
        #        save:   Yes
        #        output_root: './hirax/draco/psmc_uncorrelated_wnoise_fgfilter_kl_5thresh_nofg_'

        -   type:       draco.analysis.powerspectrum.QuadraticPSEstimation
            requires:   pm
            in:         klmodes_kl_5thresh_nofg
            out:        psmc_mv_kl_5thresh_nofg
            params:
                psname: psmc_kl_5thresh_nofg_1threshold
                pstype: minimum_variance
                save:   Yes
                output_root: './hirax/draco/psmc_minvar_wnoise_fgfilter_kl_5thresh_nofg_'
